### ISSUE TITLE
Compilation impossible

### ISSUE THREAD

**Issue by VinZz972** [hallard/teleinfo#3]
Bonjour,
J'ai commandé une carte chez vous mais je n'arrive pas à l'utiliser.
Lors de la compilation j'ai l'erreur suivante : 

`cc  -DUSE_MYSQL -DUSE_EMONCMS  -c teleinfo.c
make: cc: Command not found
Makefile:30: recipe for target 'teleinfo.o' failed
make: *** [teleinfo.o] Error 127
`
Testé sur un OrangePi sous Debian.
J'ai tenté de désactiver MySQL et Emoncms mais cela ne change rien.

Merci

**Comment by hallard** [comment]
Il manque le compilateur C, il faut l'installer avec la commande suivante

```
sudo apt-get install build-essential
```
